



server:
  port: 8080

spring:
  redis:
    host: 13.209.177.160
    port: 6379
  config:
    activate:
      on-profile: prod
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 30868b9c31c9a71f6552214d741491a6
            redirect-uri: http://happyscrolls-1206748601.ap-northeast-2.elb.amazonaws.com:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dbdbdbd.crrhuulgwkis.ap-northeast-2.rds.amazonaws.com:3306/happyscrolls?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: Chlgurtns98!

---
server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
  config:
    activate:
      on-profile: dev
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 30868b9c31c9a71f6552214d741491a6
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/happyscrollslocal
      username: root
      password: Chlgurtns98!



---




server:
  port: 8080

spring:
  config:
    activate:
      on-profile: test
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 30868b9c31c9a71f6552214d741491a6
            redirect-uri: http://happyscrolls-1206748601.ap-northeast-2.elb.amazonaws.com:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://db-master:3306/test_hps
    username: root
    password: 1234

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}