-- INSERT INTO Member (email, nickname, thumbnail)
-- values ('chs@naver.com', 'hyuksoon','img'), ('qwer@naver.com', 'pony','img'), ('asd@naver.com', 'toy','img');
--
-- INSERT INTO Article (member_id, title, body)
-- values (1l, '제목1', '내용1'),(2l, '제목2','내용2') ,(3l, '제목3','내용3');
--
-- DELIMITER $$
-- DROP PROCEDURE IF EXISTS loopInsert$$
--
-- CREATE PROCEDURE loopInsert()
-- BEGIN
--     DECLARE i INT DEFAULT 1;
--
--     WHILE i <= 500 DO
--         INSERT INTO Article(member_id, title, body)
--           VALUES(1l,concat('제목',i), concat('내용',i));
--         SET i = i + 1;
-- END WHILE;
-- END$$
-- DELIMITER $$
--
--
-- CALL loopInsert;
-- --
-- -- INSERT INTO Tag ( body)
-- -- values ("운동"),("음악"),("취미"),("맛집"),("전시");
-- --
-- -- INSERT INTO ARTICLE_TAG ( article_id,tag_id)
-- -- values ("운동"),("음악"),("취미"),("맛집"),("전시");
-- --
